package com.mycompany.peluqueriacanina.gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.peluqueriacanina.logic.LogicController;
import java.awt.Color;
import com.mycompany.peluqueriacanina.logic.Pet;
import com.mycompany.peluqueriacanina.persistence.exceptions.NonexistentEntityException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class ShowDataWindowGui extends javax.swing.JFrame {
    int xMouse, yMouse;
    LogicController logicController = null;
    private TableRowSorter<DefaultTableModel> tableSorter;

    public ShowDataWindowGui() throws UnsupportedLookAndFeelException {
        logicController = new LogicController();
        initComponents();
//        initPanelTable(); 
    }
    
    public void initPanelTable(){
//        jPanelTable.putClientProperty(FlatClientProperties.STYLE, ""
//                    + "arc:25;");
//        jTable.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
//                                + "height:30;"
//                                + "hoverBackground:null;"
//                                + "pressedBackground:null;"
//                                + "font:bold;");
//        jTable.putClientProperty(FlatClientProperties.STYLE, ""
//                                + "rowHeight:80;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelTable = new javax.swing.JPanel();
        jPanelDelete = new javax.swing.JPanel();
        jLabelDelete = new javax.swing.JLabel();
        jPanelEdit = new javax.swing.JPanel();
        jLabelEdit = new javax.swing.JLabel();
        jPanelNew = new javax.swing.JPanel();
        jLabelNew = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelSearchTitle = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jPanelBack = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelBackground.setBackground(new java.awt.Color(248, 230, 230));
        jPanelBackground.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(1100, 800));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTable.setBackground(new java.awt.Color(140, 130, 130));
        jPanelTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanelDelete.setBackground(new java.awt.Color(187, 151, 125));
        jPanelDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDelete.setPreferredSize(new java.awt.Dimension(125, 35));
        jPanelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseExited(evt);
            }
        });

        jLabelDelete.setBackground(new java.awt.Color(106, 94, 94));
        jLabelDelete.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelDelete.setForeground(new java.awt.Color(106, 94, 94));
        jLabelDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDelete.setText("Eliminar");
        jLabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDeleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteLayout = new javax.swing.GroupLayout(jPanelDelete);
        jPanelDelete.setLayout(jPanelDeleteLayout);
        jPanelDeleteLayout.setHorizontalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addComponent(jLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDeleteLayout.setVerticalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addComponent(jLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelEdit.setBackground(new java.awt.Color(187, 151, 125));
        jPanelEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEditMouseExited(evt);
            }
        });

        jLabelEdit.setBackground(new java.awt.Color(106, 94, 94));
        jLabelEdit.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelEdit.setForeground(new java.awt.Color(106, 94, 94));
        jLabelEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEdit.setText("Editar");
        jLabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelEditMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditLayout = new javax.swing.GroupLayout(jPanelEdit);
        jPanelEdit.setLayout(jPanelEditLayout);
        jPanelEditLayout.setHorizontalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEditLayout.setVerticalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelNew.setBackground(new java.awt.Color(187, 151, 125));
        jPanelNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelNew.setPreferredSize(new java.awt.Dimension(125, 35));
        jPanelNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNewMouseExited(evt);
            }
        });

        jLabelNew.setBackground(new java.awt.Color(106, 94, 94));
        jLabelNew.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelNew.setForeground(new java.awt.Color(106, 94, 94));
        jLabelNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNew.setText("Nuevo");
        jLabelNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelNewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelNewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelNewMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewLayout = new javax.swing.GroupLayout(jPanelNew);
        jPanelNew.setLayout(jPanelNewLayout);
        jPanelNewLayout.setHorizontalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelNewLayout.setVerticalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane.setBackground(new java.awt.Color(168, 137, 110));
        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane.setForeground(new java.awt.Color(168, 137, 110));

        jTable.setBackground(new java.awt.Color(140, 130, 130));
        jTable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable.setForeground(new java.awt.Color(78, 66, 66));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SELECT", "#", "NOMBRE", "RAZA", "COLOR", "ALÉRGICO", "AT.ESPECIAL", "NOMBRE DUEÑO", "CELULAR", "OBSERVACIONES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setGridColor(new java.awt.Color(140, 140, 140));
        jTable.setRowHeight(30);
        jTable.setSelectionBackground(new java.awt.Color(153, 142, 142));
        jTable.setSelectionForeground(new java.awt.Color(78, 66, 66));
        jTable.setShowGrid(true);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable.getColumnModel().getColumn(1).setMaxWidth(40);
            jTable.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable.getColumnModel().getColumn(4).setMaxWidth(120);
            jTable.getColumnModel().getColumn(5).setMaxWidth(80);
            jTable.getColumnModel().getColumn(6).setMaxWidth(80);
            jTable.getColumnModel().getColumn(7).setMaxWidth(150);
            jTable.getColumnModel().getColumn(8).setMaxWidth(150);
            jTable.getColumnModel().getColumn(9).setMaxWidth(250);
        }

        jSeparator1.setBackground(new java.awt.Color(140, 130, 130));
        jSeparator1.setForeground(new java.awt.Color(140, 130, 130));

        jLabelSearchTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelSearchTitle.setForeground(new java.awt.Color(143, 116, 94));
        jLabelSearchTitle.setText("MASCOTA");

        jTextFieldSearch.setBackground(new java.awt.Color(153, 142, 142));
        jTextFieldSearch.setForeground(new java.awt.Color(78, 66, 66));
        jTextFieldSearch.setText("Buscar...");
        jTextFieldSearch.setSelectedTextColor(new java.awt.Color(78, 66, 66));
        jTextFieldSearch.setSelectionColor(new java.awt.Color(153, 142, 142));
        jTextFieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jPanelNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addComponent(jPanelNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBackground.add(jPanelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1060, 660));

        jLabelTitle.setBackground(new java.awt.Color(106, 94, 94));
        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 62)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(168, 137, 110));
        jLabelTitle.setText("Carga de Datos");
        jPanelBackground.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 90));

        jPanelExit.setBackground(new java.awt.Color(248, 230, 230));
        jPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelExitMouseEntered(evt);
            }
        });

        jLabelExit.setBackground(new java.awt.Color(204, 166, 133));
        jLabelExit.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(204, 166, 133));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelBackground.add(jPanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 40, 40));

        jPanelBack.setBackground(new java.awt.Color(248, 230, 230));
        jPanelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBackMouseEntered(evt);
            }
        });

        jLabelBack.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(204, 166, 133));
        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setText("<");
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanelHeader.setBackground(new java.awt.Color(248, 230, 230));
        jPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelBackground.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1030, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        jPanelExit.setBackground(Color.red);
        jLabelExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        jPanelExit.setBackground(Color.decode("#F8E6E6"));
        jLabelExit.setForeground(Color.decode("#CCA685"));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jPanelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseEntered

    }//GEN-LAST:event_jPanelExitMouseEntered

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        MainWindowGui mainWindowGui = new MainWindowGui();
        mainWindowGui.setVisible(true);
        mainWindowGui.setLocationRelativeTo(null);
        mainWindowGui.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        jPanelBack.setBackground(Color.decode("#E8D7D7"));
        jLabelBack.setForeground(Color.decode("#A3856A"));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        jPanelBack.setBackground(Color.decode("#F8E6E6"));
        jLabelBack.setForeground(Color.decode("#CCA685"));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jPanelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBackMouseEntered

    }//GEN-LAST:event_jPanelBackMouseEntered

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jLabelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseClicked
        if(jTable.getRowCount() > 0){
            if(jTable.getSelectedRowCount() != 0){
                try {
                    logicController.deletePet(Integer.parseInt(String.valueOf( jTable.getValueAt(jTable.getSelectedRow(), 1))));
                    loadTable(); 
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(ShowDataWindowGui.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(jPanelBackground, "¡Mascota eliminada correctamente!");
            } else {
                JOptionPane.showMessageDialog(jPanelBackground, "No seleccionó ninguna mascota.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(jPanelBackground,"La tabla está vacía.", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelDeleteMouseClicked

    private void jLabelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseEntered
        jPanelDelete.setBackground(Color.decode("#AB8B6F"));
        jLabelDelete.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelDeleteMouseEntered

    private void jLabelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseExited
        jPanelDelete.setBackground(Color.decode("#BB987A"));
        jLabelDelete.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelDeleteMouseExited

    private void jLabelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMousePressed
        jPanelDelete.setBackground(Color.decode("#BB987A"));
        jLabelDelete.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelDeleteMousePressed

    private void jLabelDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseReleased
        jPanelDelete.setBackground(Color.decode("#AB8B6F"));
        jLabelDelete.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelDeleteMouseReleased

    private void jPanelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseEntered

    }//GEN-LAST:event_jPanelDeleteMouseEntered

    private void jPanelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseExited

    }//GEN-LAST:event_jPanelDeleteMouseExited

    private void jLabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseClicked
         if(jTable.getRowCount() > 0){
            if(jTable.getSelectedRowCount() != 0){
                int idPet = Integer.parseInt(String.valueOf( jTable.getValueAt(jTable.getSelectedRow(), 1)));
                ModificationWindowGui modificationWindowGui = new ModificationWindowGui(idPet);
                modificationWindowGui.setVisible(true);
                modificationWindowGui.setLocationRelativeTo(null);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(jPanelBackground, "No seleccionó ninguna mascota.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(jPanelBackground,"La tabla está vacía.", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEditMouseClicked

    private void jLabelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseEntered
        jPanelEdit.setBackground(Color.decode("#AB8B6F"));
        jLabelEdit.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelEditMouseEntered

    private void jLabelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseExited
        jPanelEdit.setBackground(Color.decode("#BB987A"));
        jLabelEdit.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelEditMouseExited

    private void jLabelEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMousePressed
        jPanelEdit.setBackground(Color.decode("#BB987A"));
        jLabelEdit.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelEditMousePressed

    private void jLabelEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseReleased
        jPanelEdit.setBackground(Color.decode("#AB8B6F"));
        jLabelEdit.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelEditMouseReleased

    private void jPanelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelEditMouseEntered

    private void jPanelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelEditMouseExited

    private void jLabelNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewMouseClicked
        DataWindowGui dataWindowGui = new DataWindowGui();
        dataWindowGui.setVisible(true);
        setLocationRelativeTo(null);
        dataWindowGui.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelNewMouseClicked

    private void jLabelNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewMouseEntered
        jPanelNew.setBackground(Color.decode("#AB8B6F"));
        jLabelNew.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelNewMouseEntered

    private void jLabelNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewMouseExited
        jPanelNew.setBackground(Color.decode("#BB987A"));
        jLabelNew.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelNewMouseExited

    private void jLabelNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewMousePressed
       jPanelNew.setBackground(Color.decode("#BB987A"));
        jLabelNew.setForeground(Color.decode("#6A5E5E"));
    }//GEN-LAST:event_jLabelNewMousePressed

    private void jLabelNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewMouseReleased
        jPanelNew.setBackground(Color.decode("#AB8B6F"));
        jLabelNew.setForeground(Color.decode("#332B2B"));
    }//GEN-LAST:event_jLabelNewMouseReleased

    private void jPanelNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelNewMouseEntered

    private void jPanelNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelNewMouseExited

    private void jTextFieldSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchMouseClicked
        if(jTextFieldSearch.getText().equals("Buscar...")){
            jTextFieldSearch.setText("");
        }
    }//GEN-LAST:event_jTextFieldSearchMouseClicked

    private void jTextFieldSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchMouseExited
        if(jTextFieldSearch.getText().equals("")){
            jTextFieldSearch.setText("Buscar...");
        }
    }//GEN-LAST:event_jTextFieldSearchMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadTable();
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchMouseEntered
        jTextFieldSearch.setText("");
    }//GEN-LAST:event_jTextFieldSearchMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelNew;
    private javax.swing.JLabel jLabelSearchTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelNew;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        DefaultTableModel tableModel = (DefaultTableModel) this.jTable.getModel();//new DefaultTableModel()
//        {
//            @Override
//            public boolean isCellEditable(int row, int column){
//                return false;
//            }
//        };

        //Configuration jTextField for search
        tableSorter = new TableRowSorter<>(tableModel);
        jTable.setRowSorter(tableSorter);
        //Configuration jTextField for search
        jTextFieldSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }
        });
        
        tableModel.setRowCount(0);
        //Load data from database
        List<Pet> data = logicController.getPetData();
        
        if(!data.isEmpty()){
            for(Pet pet:data){
                Object[] rowData = new Object[10];
                    rowData[0] = false;
                    rowData[1] = pet.getId();
                    rowData[2] = pet.getPetName();
                    rowData[3] = pet.getRace();
                    rowData[4] = pet.getColor();
                    rowData[5] = pet.getAlergic();
                    rowData[6] = pet.getSpeacialAtention();
                    rowData[7] = pet.getOwner().getName();
                    rowData[8] = pet.getOwner().getPhone();
                    rowData[9] = pet.getObservation();
                
                tableModel.addRow(rowData);
            }
        }
        
    }
    
    private void filterTable(){
        String text = jTextFieldSearch.getText();
        if(text.trim().length() == 0 || text.equals("Buscar...")){
            tableSorter.setRowFilter(null);
        } else {
            tableSorter.setRowFilter(RowFilter.regexFilter( text));
        }
    }
    
}
